.. |sp| replace:: Stockpyl
.. |fosct| replace:: *FoSCT*

.. |mod_demand_source| replace:: :mod:`~stockpyl.demand_source`
.. |mod_disruption_process| replace:: :mod:`~stockpyl.disruption_process`
.. |mod_eoq| replace:: :mod:`~stockpyl.eoq`
.. |mod_finite_horizon| replace:: :mod:`~stockpyl.finite_horizon`
.. |mod_gsm_helpers| replace:: :mod:`~stockpyl.gsm_helpers`
.. |mod_gsm_serial| replace:: :mod:`~stockpyl.gsm_serial`
.. |mod_gsm_tree| replace:: :mod:`~stockpyl.gsm_tree`
.. |mod_helpers| replace:: :mod:`~stockpyl.helpers`
.. |mod_instances| replace:: :mod:`~stockpyl.instances`
.. |mod_loss_functions| replace:: :mod:`~stockpyl.loss_functions`
.. |mod_meio| replace:: :mod:`~stockpyl.meio`
.. |mod_newsvendor| replace:: :mod:`~stockpyl.newsvendor`
.. |mod_optimization| replace:: :mod:`~stockpyl.optimization`
.. |mod_policy| replace:: :mod:`~stockpyl.policy`
.. |mod_rq| replace:: :mod:`~stockpyl.rq`
.. |mod_ss| replace:: :mod:`~stockpyl.ss`
.. |mod_ssm_serial| replace:: :mod:`~stockpyl.ssm_serial`
.. |mod_supply_chain_network| replace:: :mod:`~stockpyl.supply_chain_network`
.. |mod_supply_chain_node| replace:: :mod:`~stockpyl.supply_chain_node`
.. |mod_supply_uncertainty| replace:: :mod:`~stockpyl.supply_uncertainty`
.. |mod_wagner_whitin| replace:: :mod:`~stockpyl.wagner_whitin`

.. |rq| replace:: :math:`(r,Q)`
.. |ss| replace:: :math:`(s,S)`

.. |copy| unicode:: U+000A9 .. COPYRIGHT SIGN