.. |sp| replace:: Stockpyl
.. |fosct| replace:: *FoSCT*

.. |fosct_notation| replace:: The notation and references (equations, sections, examples, etc.) used below refer to Snyder and Shen, *Fundamentals of Supply Chain Theory* (|fosct|), 2nd edition (2019).
.. |node_stage| replace:: The terms "node" and "stage" are used interchangeably in the documentation.

.. |mod_demand_source| replace:: :mod:`~stockpyl.demand_source`
.. |mod_disruption_process| replace:: :mod:`~stockpyl.disruption_process`
.. |mod_eoq| replace:: :mod:`~stockpyl.eoq`
.. |mod_finite_horizon| replace:: :mod:`~stockpyl.finite_horizon`
.. |mod_gsm_helpers| replace:: :mod:`~stockpyl.gsm_helpers`
.. |mod_gsm_serial| replace:: :mod:`~stockpyl.gsm_serial`
.. |mod_gsm_tree| replace:: :mod:`~stockpyl.gsm_tree`
.. |mod_helpers| replace:: :mod:`~stockpyl.helpers`
.. |mod_instances| replace:: :mod:`~stockpyl.instances`
.. |mod_loss_functions| replace:: :mod:`~stockpyl.loss_functions`
.. |mod_meio_general| replace:: :mod:`~stockpyl.meio_general`
.. |mod_newsvendor| replace:: :mod:`~stockpyl.newsvendor`
.. |mod_optimization| replace:: :mod:`~stockpyl.optimization`
.. |mod_policy| replace:: :mod:`~stockpyl.policy`
.. |mod_rq| replace:: :mod:`~stockpyl.rq`
.. |mod_sim| replace:: :mod:`~stockpyl.sim`
.. |mod_sim_io| replace:: :mod:`~stockpyl.sim_io`
.. |mod_ss| replace:: :mod:`~stockpyl.ss`
.. |mod_ssm_serial| replace:: :mod:`~stockpyl.ssm_serial`
.. |mod_supply_chain_network| replace:: :mod:`~stockpyl.supply_chain_network`
.. |mod_supply_chain_node| replace:: :mod:`~stockpyl.supply_chain_node`
.. |mod_supply_chain_product| replace:: :mod:`~stockpyl.supply_chain_product`
.. |mod_node_state_vars| replace:: :mod:`~stockpyl.node_state_vars`
.. |mod_supply_uncertainty| replace:: :mod:`~stockpyl.supply_uncertainty`
.. |mod_wagner_whitin| replace:: :mod:`~stockpyl.wagner_whitin`

.. |class_network| replace:: :class:`~stockpyl.supply_chain_network.SupplyChainNetwork`
.. |class_node| replace:: :class:`~stockpyl.supply_chain_node.SupplyChainNode`
.. |class_product| replace:: :class:`~stockpyl.supply_chain_node.SupplyChainProduct`
.. |class_state_vars| replace:: :class:`~stockpyl.supply_chain_network.NodeStateVars`
.. |class_demand_source| replace:: :class:`~stockpyl.demand_source.DemandSource`
.. |class_disruption_process| replace:: :class:`~stockpyl.disruption_process.DisruptionProcess`
.. |class_policy| replace:: :class:`~stockpyl.policy.Policy`

.. |rq| replace:: :math:`(r,Q)`
.. |ss| replace:: :math:`(s,S)`

.. |copy| unicode:: U+000A9 .. COPYRIGHT SIGN